// stubs/ui-svelte/card/CardTitle.svelte
<script lang="ts">
    import type { Snippet } from 'svelte';
    import { cn } from '@/lib/utils';

    let {
        class: className = '',
        children,
    }: {
        class?: string;
        children?: Snippet;
    } = $props();
</script>

<h3 data-slot="card-title" class={cn('leading-none font-bold text-black dark:text-white', className)}>
    {@render children?.()}
</h3>

// stubs/ui/card/CardTitle.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import { cn } from "@/lib/utils"

const props = defineProps<{
  class?: HTMLAttributes["class"]
}>()
</script>

<template>
  <h3
    data-slot="card-title"
    :class="cn('leading-none font-bold text-black dark:text-white', props.class)"
  >
    <slot />
  </h3>
</template>
